name: kafiil
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_easyloading: ^3.0.5
  hive: ^2.2.3
  font_awesome_flutter: ^10.6.0
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  intl: ^0.19.0
  multi_dropdown: ^2.1.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat-bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat-semi-bold.ttf
          weight: 600
        - asset: assets/fonts/montserrat-medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat-regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat-light.ttf
          weight: 300


